---
swagger: "2.0"
info:
  title: Admin Account Credit Service
  version: 0.0.1
paths:
  /admin/users/{userId}/accountcredit:
    get:
      summary: Lookup a users account credit
      produces:
        - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: Authorization
          in: header
          description: The bearer token from the Auth server describing the user.
          type: string
          required: true
          format: "/^Bearer .+/"
          x-elevation: none
        - name: userId
          type: string
          in: path
          required: true
      responses:
        200:
          description: userId's Credit history
          schema:
            $ref: CreditHistory
        401:
          description: Not authenticated
        403:
          description: Insufficient privileges (needs CSR or CSM role)
    
  /admin/users/{userId}/accountcredit/credits:
    post:
      summary: Credit a user's account
      description: add credit to user's account
      parameters:
        - name: Authorization
          in: header
          description: The bearer token from the Auth server describing the user.
          type: string
          required: true
          format: "/^Bearer .+/"
          x-elevation: none
        - name: userId
          type: string
          in: path
          required: true
        - name: body
          required: true
          in: body
          description: add credit details
          schema:
            $ref: Credit
      responses:
        204:
          description: Account credit successfully updated
        401:
          description: Not authenticated
        403:
          description: User not authorised (needs CSR/CSM role)
        404:
          description: User not found
              
  /admin/users/{userId}/accountcredit/debits:
    post:
      summary: Debit a user's account
      consumes:
       - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: Authorization
          in: header
          description: The bearer token from the Auth server describing the user.
          type: string
          required: true
          format: "/^Bearer .+/"
          x-elevation: none
        - name: userId
          required: true
          type: string
          in: path
        - name: body
          required: true
          in: body
          description: debit details
          schema:
            $ref: Debit
      responses:
        204:
          description: Account debit successfully update
        400:
          description: Amount is non-negative, or currency is not GBP
        400:
          description: Insufficient funds
        401:
          description: Not authenticated
        403:
          description: User not authorised (needs CSR/CSM role)
        404:
          description: User not found
              
definitions:
  CreditHistory:
    title: Credit history (ordered by `dateTime` descendingly)
    properties:
      balance:
        title: The user's net credit balance (credits minus debits)
        type: number
        minimum: 0
      items:
        type: array
        items:
          oneOf:
            - $ref: Credit
            - $ref: Debit

  Credit:
    title: Credit
    properties:
      requestId:
        title: RequestId
        type: string
        description: An identifier used to make this POST idempotent. If the service has already applied a credit change with this ID, this request does not add more credit, and returns 204. This SHOULD be a GUID.
      type:
        title: Type
        type: string
        enum: [Credit]
        readOnly: true
      dateTime:
        title: When the credit was applied
        type: string
        format: date-time
        readOnly: true
      amount:
        $ref: PositiveAmount
      reason:
        title: The reason given for the credit
        type: string
        readOnly: true
        enum: [GoodwillBookIssue,GoodwillTechnicalIssue,GoodwillServiceIssue,GoodwillCustomerRetention,CreditRefund,StaffCredit,CreditVoucherCode,Hudl2Promotion]
      issuer:
        title: The issuer's details, at the time of issuance (only visible to CSM)
        $ref: Issuer

  Issuer:
    description: A person who issues credit to a customer (a CSR or a CSM)
    readOnly: true
    properties:
      name:
        type: string
      roles:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [csr, csm]

  Debit:
    title: Debit
    properties:
      requestId:
        title: RequestId
        type: string
        description: An identifier used to make this POST idempotent. If the service has already applied a debit change with this ID, this request does not add more debit, and returns 204. This SHOULD be a GUID.
      type:
        title: Type
        type: string
        enum: [Debit]
        readOnly: true
      dateTime:
        title: When the debit was applied
        type: string
        format: date-time
        readOnly: true
      amount:
        $ref: PositiveAmount

  Amount:
    title: Amount
    properties:
      currency:
        title: Currency
        type: string
        enum: [GBP]
      value:
        title: Value
        type: number
        minimum: 0

  PositiveAmount:
    title: Amount
    properties:
      currency:
        title: Currency
        type: string
        enum: [GBP]
      value:
        title: Value
        type: number
        minimum: 0
        exclusiveMinimum: true
