---
swagger: "2.0"
info:
  title: Admin Account Credit Service
  version: 0.0.1
paths:
  /admin/users/{userId}/accountcredit:
    get:
      summary: Lookup a users account credit
      produces:
        - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: Authorization
          in: header
          description: The bearer token from the Auth server describing the user.
          type: string
          required: true
          format: "/^Bearer .+/"
          x-elevation: none
        - name: userId
          type: string
          in: path
          required: true
      responses:
        200:
          description: userId's Credit history
          schema:
            $ref: CreditHistory
        401:
          description: Not authenticated
        403:
          description: Insufficient privileges (needs CSR or CSM role)
        404:
          description: User not found
    
  /admin/users/{userId}/accountcredit/credits:
    post:
      summary: Credit a user's account
      description: add credit to user's account
      parameters:
        - name: Authorization
          in: header
          description: The bearer token from the Auth server describing the user.
          type: string
          required: true
          format: "/^Bearer .+/"
          x-elevation: none
        - name: userId
          type: string
          in: path
          required: true
        - name: body
          required: true
          in: body
          description: add credit details
          schema:
            $ref: AddCreditRequest
            
      responses:
        201:
          description: Account credit successfully update
          schema:
            $ref: AddCreditResponse
        401:
          description: Not authenticated
        404:
          description: User not found
              
  /admin/users/{userId}/accountcredit/debits:
    post:
      summary: Debit a user's account
      consumes:
       - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: Authorization
          in: header
          description: The bearer token from the Auth server describing the user.
          type: string
          required: true
          format: "/^Bearer .+/"
          x-elevation: none
        - name: userId
          required: true
          type: string
          in: path
        - name: body
          required: true
          in: body
          description: add debit details
          schema:
            $ref: AddDebitRequest

      responses:
        204:
          description: Account debit successfully update
        401:
          description: Not authenticated
        404:
          description: User not found
              
definitions:
  CreditHistory:
    title: Credit history (ordered by `dateTime` descendingly)
    properties:
      balance:
        title: The user's net credit balance (credits minus debits)
        type: number
        minimum: 0
      items:
        type: array
        items:
          oneOf:
            - $ref: Credit
            - $ref: Debit

  Credit:
    title: Credit
    properties:
      type:
        title: Type
        type: string
        enum: [credit]
      dateTime:
        title: When the credit was applied
        type: string
        format: date-time
      amount:
        $ref: Amount
      reason:
        title: The reason given for the credit
        type: string
      issuer:
        title: The issuer's details, at the time of issuance (only visible to CSM)
        $ref: Issuer

  Issuer:
    description: A person who issues credit to a customer (a CSR or a CSM)
    properties:
      name:
        type: string
      roles:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [csr, csm]

  Debit:
    title: Debit
    properties:
      type:
        title: Type
        type: string
        enum: [debit]
      dateTime:
        title: When the debit was applied
        type: string
        format: date-time
      amount:
        $ref: Amount

  Amount:
    title: Amount
    properties:
      currency:
        title: Currency
        type: string
        enum: [GBP]
      value:
        title: Value
        type: number
        minimum: 0

  AddCreditRequest:
     title: AddCreditRequest
     properties:
          requestId:
            title: RequestId
            type: string
            description: identifier used to make this Post idempotent. If the service has already applied a credit change with this ID, this request does not add more credit, and returns 201.
          value:
            title: Value
            type: number
            minimum: 0
            exclusiveMinimum: true
          reason:
            title: The reason given for the credit
            type: string
            enum: [GoodwillBookIssue,GoodwillTechnicalIssue,GoodwillServiceIssue,GoodwillCustomerRetention,CreditRefund,StaffCredit,CreditVoucherCode,Hudl2Promotion]
  AddDebitRequest:
     title: AddDebitRequest
     properties:
          requestId:
            title: RequestId
            type: string
            description: identifier used to make this Post idempotent. If the service has already applied a debit change with this ID, this request does not add more debit, and returns 201.
          value:
            title: Value
            type: number
            minimum: 0
            exclusiveMinimum: true
          
  AddCreditResponse:
      title: AddCreditResponse
      properties:
        requestId:
          title: RequestId
          type: string
        amount:
            $ref: Amount
