---
swagger: "2.0"
info:
  title: Admin Account Credit Service
  version: 0.0.1
paths:
  /admin/users/{userId}/credit:
    get:
      summary: Lookup a users account credit
      produces:
        - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: Authorization
          in: header
          description: The bearer token from the Auth server describing the user.
          type: string
          required: true
          format: "/^Bearer .+/"
          x-elevation: none
        - name: userId
          type: string
          in: path
          required: true
      responses:
        200:
          description: userId's Credit history
          schema:
            $ref: CreditHistory
        401:
          description: Not authenticated
        403:
          description: Insufficient privileges (needs CSR or CSM role)
        404:
          description: User not found
    post:
      summary: Credit an user's account
      description: add credit to user's account
      parameters:
        - name: Authorization
          in: header
          description: The bearer token from the Auth server describing the user.
          type: string
          required: true
          format: "/^Bearer .+/"
          x-elevation: none
        - name: userId
          type: string
          in: path
          required: true
        - name: body
          required: true
          in: body
          description: add credit details
          schema:
            $ref: AddCreditDebitRequest
            
      responses:
        204:
          description: Account credit successfully update
          schema:
            $ref: AddCreditDebitResponse
        401:
          description: Not authenticated
        404:
          description: User not found
              
  /admin/users/{userId}/debit:
    put:
      summary: Debit a user's account
      consumes:
       - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: userId
          required: true
          type: string
          in: path
        - name: id
          required: true
          description: identifier used to make this PUT idempotent. If the service has already applied a credit change with this ID, this request does not add more credit, and returns 204.
          type: string
          in: formData
        - name: amount_change
          type: integer
          in: formData
          required: true
          

      responses:
        204:
          description: Account credit successfully update
          examples:
            application/json: |
              { "amount_change": 2000,
                "id": "4f87e333-32c7-4d40-a3cd-7da58345069e"
              }
              
definitions:
  CreditHistory:
    title: Credit history (ordered by `dateTime` descendingly)
    properties:
      balance:
        title: The user's net credit balance (credits minus debits)
        type: number
        minimum: 0
      items:
        type: array
        items:
          oneOf:
            - $ref: Credit
            - $ref: Debit

  Credit:
    title: Credit
    properties:
      type:
        title: Type
        type: string
        enum: [credit]
      dateTime:
        title: When the credit was applied
        type: string
        format: date-time
      amount:
        $ref: Amount
      reason:
        title: The reason given for the credit
        type: string
      issuer:
        title: The issuer's details, at the time of issuance (only visible to CSM)
        $ref: Issuer

  Issuer:
    description: A person who issues credit to a customer (a CSR or a CSM)
    properties:
      name:
        type: string
      roles:
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [csr, csm]

  Debit:
    title: Debit
    properties:
      type:
        title: Type
        type: string
        enum: [debit]
      dateTime:
        title: When the debit was applied
        type: string
        format: date-time
      amount:
        $ref: Amount

  Amount:
    title: Amount
    properties:
      currency:
        title: Currency
        type: string
        enum: [GBP]
      value:
        title: Value
        type: number
        minimum: 0
        
  AddCreditDebitRequest:
     title: AddCreditDebit
     properties:
          requestId:
            title: RequestId
            type: string
            description: identifier used to make this Post idempotent. If the service has already applied a credit change with this ID, this request does not add more credit, and returns 204.
          amount:
            $ref: Amount
          reason:
            title: The reason given for the credit
            type: string
          type:
            title: Type
            type: string
            enum: [credit,debit]
          
  AddCreditDebitResponse:
      title: AddCreditDebitResponse
      properties:
        id:
          title: Id
          type: string
        amount:
            $ref: Amount
        type:
            title: Type
            type: string
            enum: [credit,debit]
