---
swagger: "2.0"
info:
  title: Admin Account Credit Service
  version: 0.0.1
paths:
  /admin/users/{userId}/credit:
    get:
      summary: Lookup a users account credit
      produces:
        - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: userId
          type: string
          in: path
          required: true
      responses:
        200:
          description: userId's Credit history
          schema:
            $ref: CreditHistory
        401:
          description: Not authenticated
        403:
          description: Insufficient privileges (needs CSR or CSM role)
        404:
          description: User not found
    put:
      summary: Credit a user's account
      consumes:
       - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: userId
          required: true
          type: string
          in: path
        - name: id
          required: true
          description: identifier used to make this PUT idempotent. If the service has already applied a credit change with this ID, this request does not add more credit, and returns 204.
          type: string
          in: formData
        - name: amount_change
          type: integer
          in: formData
          required: true
        - name: credited_by
          required: true
          type: string
          in: formData
        - name: reason
          required: true
          type: string
          in: formData
          

      responses:
        204:
          description: Account credit successfully update
          examples:
            application/json: |
              { "amount_change": 2000,
                "id": "4f87e333-32c7-4d40-a3cd-7da58345069e"
              }
              
  /admin/users/{userId}/debit:
    put:
      summary: Debit a user's account
      consumes:
       - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: userId
          required: true
          type: string
          in: path
        - name: id
          required: true
          description: identifier used to make this PUT idempotent. If the service has already applied a credit change with this ID, this request does not add more credit, and returns 204.
          type: string
          in: formData
        - name: amount_change
          type: integer
          in: formData
          required: true
          

      responses:
        204:
          description: Account credit successfully update
          examples:
            application/json: |
              { "amount_change": 2000,
                "id": "4f87e333-32c7-4d40-a3cd-7da58345069e"
              }
              
definitions:
  CreditHistory:
    title: Credit history (ordered by `dateTime` descendingly)
    properties:
      balance:
        title: The user's net credit balance (credits minus debits)
        type: number
        minimum: 0
      items:
        type: array
        items:
          oneOf:
            - $ref: Credit
            - $ref: Debit

  Credit:
    title: Credit
    properties:
      type:
        title: Type
        type: string
        enum: [credit]
      dateTime:
        title: When the credit was applied
        type: string
        format: date-time
      amount:
        $ref: Amount
      reason:
        title: The reason given for the credit
        type: string
      issuerName:
        title: The issuing CSR/CSM's name, at the time of issuance (only visible to CSM)
        type: string
      issuerRoles:
        title: The issuing CSR/CSM's roles, at the time of issuance (only visible to CSM)
        type: array
        uniqueItems: true
        items:
          type: string
          enum: [csr, csm]

  Debit:
    title: Debit
    properties:
      type:
        title: Type
        type: string
        enum: [debit]
      dateTime:
        title: When the debit was applied
        type: string
        format: date-time
      amount:
        $ref: Amount

  Amount:
    title: Amount
    properties:
      currency:
        title: Currency
        type: string
        enum: [GBP]
      value:
        title: Value
        type: number
        minimum: 0
