---
swagger: "2.0"
info:
  title: Admin Account Credit Service
  version: 1.0.0
paths:
  /admin/users/{user_id}/credit:
    get:
      summary: Lookup a users account credit
      produces:
        - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: user_id
          type: string
          in: path
          required: true
      responses:
        200:
          description: user_id's Credit history
          schema:
            $ref: CreditHistory
        401:
          description: Not authenticated
        403:
          description: Insufficient privileges (needs CSR or CSM role)
        404:
          description: User not found
    put:
      summary: Credit a user's account
      consumes:
       - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: user_id
          required: true
          type: string
          in: path
        - name: id
          required: true
          description: identifier used to make this PUT idempotent. If the service has already applied a credit change with this ID, this request does not add more credit, and returns 204.
          type: string
          in: formData
        - name: amount_change
          type: integer
          in: formData
          required: true
        - name: credited_by
          required: true
          type: string
          in: formData
        - name: reason
          required: true
          type: string
          in: formData
          

      responses:
        204:
          description: Account credit successfully update
          examples:
            application/json: |
              { "amount_change": 2000,
                "id": "4f87e333-32c7-4d40-a3cd-7da58345069e"
              }
              
  /admin/users/{user_id}/debit:
    put:
      summary: Debit a user's account
      consumes:
       - application/vnd.blinkbox.books.v2+json
      parameters:
        - name: user_id
          required: true
          type: string
          in: path
        - name: id
          required: true
          description: identifier used to make this PUT idempotent. If the service has already applied a credit change with this ID, this request does not add more credit, and returns 204.
          type: string
          in: formData
        - name: amount_change
          type: integer
          in: formData
          required: true
          

      responses:
        204:
          description: Account credit successfully update
          examples:
            application/json: |
              { "amount_change": 2000,
                "id": "4f87e333-32c7-4d40-a3cd-7da58345069e"
              }
              
definitions:
  CreditHistory:
    title: Credit history
    properties:
      credits:
        $ref: CreditList
      debits:
        $ref: DebitList
  CreditList:
    title: List of credits
    properties:
      items:
        type: array
        items:
          $ref: Credit
  DebitList:
    title: List of debits
    properties:
      items:
        type: array
        items:
          $ref: Debit
  Credit:
    title: Credit
    properties:
      dateTime:
        title: When the credit was applied
        type: string
      amountInPence:
        title: The credit's amount, in pence
        type: integer
      reason:
        title: The reason given for the credit
        type: string
      issuerName:
        title: The issuing CSR/CSM's name, at the time of issuance (only visible to CSM)
        type: string
      issuerRole:
        title: The issuing CSR/CSM's roles, at the time of issuance (only visible to CSM)
        type: string
  Debit:
    title: Debit
    properties:
      dateTime:
        title: When the debit was applied
        type: string
      amountInPence:
        title: The debit's amount, in pence
        type: integer
        
