default: -p ci-regression-dev-int

ci-smoke-dev-int: --tags @smoke --tags ~@manual SERVER=dev_int --strict
ci-regression-dev-int: --tags ~@in-progress --tags ~@manual SERVER=dev_int --strict

dev: --tags ~@in-progress --tags ~@manual SERVER=local --strict --format pretty
